package net.projecteuler;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//                      1,2,3,5,8,13,21,34,55,89
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class Problem002 {

    public long sumOfAllFibonacciValuesForMaxLastValue(final int maxValue) {
        int sum = 0;

        int previousValue = 1;
        int currentValue = 2;
        while (currentValue <= maxValue) {
            if (currentValue % 2 == 0) {
                sum += currentValue;
            }
            int tempValue = currentValue;
            currentValue = previousValue + currentValue;
            previousValue = tempValue;
        }

        return sum;
    }
}
