# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                      1,2,3,5,8,13,21,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_even_fibonacci_v1(max_value):
    sum = 0

    previous_value = 1
    current_value = 2
    while current_value < max_value:
        if current_value % 2 == 0:
            sum += current_value

        temp_value = current_value
        current_value = previous_value + current_value
        previous_value = temp_value

    return sum

def sum_even_fibonacci_v2(max_value):
    sum = 0

    previous_value = 1
    current_value = 2
    while current_value < max_value:
        if current_value % 2 == 0:
            sum += current_value

        current_value, previous_value = previous_value + current_value, current_value

    return sum